name: Deploy wp-content to Server

on:
  push:
    branches:
      - main  # Запускаем Action при каждом пуше в ветку staging


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USER: "webdata"  # replace with the actual SSH user
      SSH_HOST: "18.206.91.6"   # replace with the actual IP of your server
      TARGET_PATH: "/var/www/html/test/test"  # replace with the actual target path

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: "18.206.64.165"
          user: "webdata"
          private_key: ${{secrets.SSH_KEY}}
          command: |
            cd $TARGET_PATH


        #https://github.com/webfactory/ssh-agent
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_KEY }}

#      - name: Copy wp-content to server
#        run: |
#          #scp -o StrictHostKeyChecking=no -r wp-content ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_PATH }}
#          #scp -o StrictHostKeyChecking=no -r wp-content $SSH_USER@$SSH_HOST:$TARGET_PATH
#          cd $TARGET_PATH
#          git clone


